version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - net

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1
    networks:
      - net
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client2
    networks:
      - net
    depends_on:
      - server

networks:
  net:
    driver: bridge
